-- Create glossary terms table for interactive definitions
CREATE TABLE public.glossary_terms (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  term TEXT NOT NULL UNIQUE,
  definition TEXT NOT NULL,
  category TEXT DEFAULT 'general',
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.glossary_terms ENABLE ROW LEVEL SECURITY;

-- RLS policies - terms are public readable
CREATE POLICY "Anyone can view active glossary terms" 
ON public.glossary_terms 
FOR SELECT 
USING (is_active = true);

-- Insert popular real estate investment terms
INSERT INTO public.glossary_terms (term, definition, category) VALUES 
  ('Off-Market Properties', 'Properties that are not publicly listed on the MLS, often found through networking, direct outreach, or specialized platforms.', 'sourcing'),
  ('BRRRR', 'Buy, Rehab, Rent, Refinance, Repeat - A real estate investment strategy for building wealth through rental properties.', 'strategies'),
  ('ARV', 'After Repair Value - The estimated value of a property after all planned improvements and repairs are completed.', 'analysis'),
  ('Wholesaling', 'A real estate strategy where investors find discounted properties and assign the contract to another buyer for a fee.', 'strategies'),
  ('Fix & Flip', 'Purchasing distressed properties, renovating them, and selling them quickly for a profit.', 'strategies'),
  ('Cap Rate', 'Capitalization rate - A metric used to evaluate the potential return on investment for income-producing properties.', 'analysis'),
  ('NOI', 'Net Operating Income - The total income from a property minus operating expenses, excluding mortgage payments.', 'analysis'),
  ('LTV', 'Loan-to-Value ratio - The percentage of a property''s value that is financed through a mortgage or loan.', 'financing'),
  ('Hard Money Lender', 'Private lenders who provide short-term, asset-based loans typically used for real estate investments.', 'financing'),
  ('Due Diligence', 'The comprehensive investigation and analysis of a property before finalizing a purchase to identify potential risks.', 'legal'),
  ('1031 Exchange', 'A tax-deferred exchange allowing investors to swap one investment property for another of like-kind.', 'legal'),
  ('Cash Flow', 'The net amount of money generated by a rental property after all expenses are deducted from rental income.', 'analysis'),
  ('Motivated Seller', 'A property owner who needs to sell quickly due to financial distress, relocation, or other urgent circumstances.', 'sourcing'),
  ('Distressed Property', 'Real estate in poor condition or facing foreclosure, often available at below-market prices.', 'sourcing'),
  ('Market Analysis', 'Research and evaluation of local real estate market conditions, trends, and comparable property values.', 'analysis');

-- Create indexes for better performance
CREATE INDEX idx_glossary_terms_category ON public.glossary_terms(category);
CREATE INDEX idx_glossary_terms_active ON public.glossary_terms(is_active);

-- Add trigger for updated_at
CREATE TRIGGER update_glossary_terms_updated_at
  BEFORE UPDATE ON public.glossary_terms
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();